### ISSUE TITLE
Consider changing generator from `ts-protoc-gen` to `protoc-gen-ts`

### ISSUE THREAD

**Issue by dylanratcliffe** [overmindtech/sdp-js#12]
The code generated by [`protoc-gen-ts`](https://github.com/thesayyn/protoc-gen-ts) is much nicer. However as far as I can tell it doesn't play nicely with well-known types such as google.protobuf.Struct which is a dealbreaker for me. See this conversation: https://github.com/thesayyn/protoc-gen-ts/discussions/129

If this is resolved though it'll definitely be better to change

**Comment by getinnocuous** [comment]
Fixed as part of #41
