### ISSUE TITLE
Remove all of the auto-discovery stuff from `sdp-js` 

### ISSUE THREAD

**Issue by getinnocuous** [overmindtech/sdp-js#224]
> This has been implemented here: > https://github.com/overmindtech/sdp/blob/main/account.proto#L64-L65
>
> Next tasks are:

> * [x] Switch over to using this API in the frontend to pre-populate the available types
> * [ ] Remove all of the auto-discovery stuff from `sdp-js` (TODO CREATE TICKET)
> * [ ] Remove all of the auto-discovery stuff from `discovery`, this means getting rid of > > those meta-types for `overmind-type` etc. (TODO CREATE TICKET)

_Originally posted by @dylanratcliffe in https://github.com/overmindtech/frontend/issues/1564#issuecomment-2513972283_

**Comment by dylanratcliffe** [comment]
Most of the querying logic is implemented here: https://github.com/overmindtech/sdp-js/blob/main/src/source-discovery.ts
