### ISSUE TITLE
Upgrade @bufbuild/protbuf to v2

### ISSUE THREAD

**Issue by dylanratcliffe** [overmindtech/sdp-js#225]
`sdp-js` has a PR to update protobuf to V2: https://github.com/overmindtech/sdp-js/pull/203 This will require some additional work before it can be merged, including updating the frontend: https://github.com/overmindtech/frontend/pull/1453 and potentially upgrading the generation libraries used in [sdp](https://github.com/overmindtech/sdp) (though I'm nil 100% sure about that)

This should all be merged assuming it works, and any cleanup done as part of the major version upgrade. Also might as well close a bunch of the other PRs while you're at it

**Comment by getinnocuous** [comment]
Completed in #228
