### ISSUE TITLE
Separate stuff into own files

### ISSUE THREAD

**Issue by dylanratcliffe** [overmindtech/sdp-js#4]
I tried this initially and even though it passed all the tests I was getting an error at runtime:

"X is not a Constructor"

When trying to use the constructors of any of the objects from the different file, even though they were being imported and re-exported in the index.ts file. I looked at a few different ways to try and get it to export them correctly and the only way that I could get it to work was to have everything in the one file, which sucks

**Comment by getinnocuous** [comment]
Closed by #23
