### ISSUE TITLE
Look into Buf's protobuf generators to solve the horrible javascript API

### ISSUE THREAD

**Issue by dylanratcliffe** [overmindtech/sdp-js#41]
The API that is generate by the current generator is awful. We have considered another one in #12. But it doesn't support structs which is a dealbreaker. Maybe this one is a better option: https://buf.build/blog/protobuf-es-the-protocol-buffers-typescript-javascript-runtime-we-all-deserve

**Comment by getinnocuous** [comment]
![Screenshot 2023-03-02 at 08 44 28](https://user-images.githubusercontent.com/9265979/222377038-2c5b2c7e-b771-4913-b8c7-2966343f0983.png)
All for using this if it means we can remove the google protobuf dep. Chunky fella!
